/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  MeasurementType,
  MeasurementTypeCreateForm
} from '../../model'
import { farmfarmAxiosInstance } from '../../../axios/axios_instance';
import type { ErrorType, BodyType } from '../../../axios/axios_instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


export const findAllMeasurementType = (
    
 options?: SecondParameter<typeof farmfarmAxiosInstance>,signal?: AbortSignal
) => {
      
      
      return farmfarmAxiosInstance<MeasurementType[]>(
      {url: `/measurementTypes`, method: 'GET', signal
    },
      options);
    }
  

export const getFindAllMeasurementTypeQueryKey = () => {
    return [`/measurementTypes`] as const;
    }

    
export const getFindAllMeasurementTypeQueryOptions = <TData = Awaited<ReturnType<typeof findAllMeasurementType>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findAllMeasurementType>>, TError, TData>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllMeasurementTypeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllMeasurementType>>> = ({ signal }) => findAllMeasurementType(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllMeasurementType>>, TError, TData> & { queryKey: QueryKey }
}

export type FindAllMeasurementTypeQueryResult = NonNullable<Awaited<ReturnType<typeof findAllMeasurementType>>>
export type FindAllMeasurementTypeQueryError = ErrorType<unknown>

export const useFindAllMeasurementType = <TData = Awaited<ReturnType<typeof findAllMeasurementType>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findAllMeasurementType>>, TError, TData>, request?: SecondParameter<typeof farmfarmAxiosInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getFindAllMeasurementTypeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createMeasurementType = (
    measurementTypeCreateForm: BodyType<MeasurementTypeCreateForm>,
 options?: SecondParameter<typeof farmfarmAxiosInstance>,) => {
      
      
      return farmfarmAxiosInstance<string>(
      {url: `/measurementTypes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: measurementTypeCreateForm
    },
      options);
    }
  


export const getCreateMeasurementTypeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMeasurementType>>, TError,{data: BodyType<MeasurementTypeCreateForm>}, TContext>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMeasurementType>>, TError,{data: BodyType<MeasurementTypeCreateForm>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMeasurementType>>, {data: BodyType<MeasurementTypeCreateForm>}> = (props) => {
          const {data} = props ?? {};

          return  createMeasurementType(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMeasurementTypeMutationResult = NonNullable<Awaited<ReturnType<typeof createMeasurementType>>>
    export type CreateMeasurementTypeMutationBody = BodyType<MeasurementTypeCreateForm>
    export type CreateMeasurementTypeMutationError = ErrorType<unknown>

    export const useCreateMeasurementType = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMeasurementType>>, TError,{data: BodyType<MeasurementTypeCreateForm>}, TContext>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createMeasurementType>>,
        TError,
        {data: BodyType<MeasurementTypeCreateForm>},
        TContext
      > => {

      const mutationOptions = getCreateMeasurementTypeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    