/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Greenhouse,
  GreenhouseCreateForm
} from '../../model'
import { farmfarmAxiosInstance } from '../../../axios/axios_instance';
import type { ErrorType, BodyType } from '../../../axios/axios_instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


export const findAllGreenhouses = (
    
 options?: SecondParameter<typeof farmfarmAxiosInstance>,signal?: AbortSignal
) => {
      
      
      return farmfarmAxiosInstance<Greenhouse[]>(
      {url: `/greenhouses`, method: 'GET', signal
    },
      options);
    }
  

export const getFindAllGreenhousesQueryKey = () => {
    return [`/greenhouses`] as const;
    }

    
export const getFindAllGreenhousesQueryOptions = <TData = Awaited<ReturnType<typeof findAllGreenhouses>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findAllGreenhouses>>, TError, TData>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllGreenhousesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllGreenhouses>>> = ({ signal }) => findAllGreenhouses(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllGreenhouses>>, TError, TData> & { queryKey: QueryKey }
}

export type FindAllGreenhousesQueryResult = NonNullable<Awaited<ReturnType<typeof findAllGreenhouses>>>
export type FindAllGreenhousesQueryError = ErrorType<unknown>

export const useFindAllGreenhouses = <TData = Awaited<ReturnType<typeof findAllGreenhouses>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findAllGreenhouses>>, TError, TData>, request?: SecondParameter<typeof farmfarmAxiosInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getFindAllGreenhousesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createGreenhouse = (
    greenhouseCreateForm: BodyType<GreenhouseCreateForm>,
 options?: SecondParameter<typeof farmfarmAxiosInstance>,) => {
      
      
      return farmfarmAxiosInstance<string>(
      {url: `/greenhouses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: greenhouseCreateForm
    },
      options);
    }
  


export const getCreateGreenhouseMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGreenhouse>>, TError,{data: BodyType<GreenhouseCreateForm>}, TContext>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createGreenhouse>>, TError,{data: BodyType<GreenhouseCreateForm>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGreenhouse>>, {data: BodyType<GreenhouseCreateForm>}> = (props) => {
          const {data} = props ?? {};

          return  createGreenhouse(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGreenhouseMutationResult = NonNullable<Awaited<ReturnType<typeof createGreenhouse>>>
    export type CreateGreenhouseMutationBody = BodyType<GreenhouseCreateForm>
    export type CreateGreenhouseMutationError = ErrorType<unknown>

    export const useCreateGreenhouse = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGreenhouse>>, TError,{data: BodyType<GreenhouseCreateForm>}, TContext>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createGreenhouse>>,
        TError,
        {data: BodyType<GreenhouseCreateForm>},
        TContext
      > => {

      const mutationOptions = getCreateGreenhouseMutationOptions(options);

      return useMutation(mutationOptions);
    }
    