export const importData = {
    VITE_FARMFARM_SERVER_URL: import.meta.env.VITE_FARMFARM_SERVER_URL,
    VITE_AUTH_SERVER_URL: import.meta.env.VITE_AUTH_SERVER_URL,
    VITE_AUTH_SERVER_REALM: import.meta.env.VITE_AUTH_SERVER_REALM,
    VITE_SWAGGER_DOCS_API_URI: import.meta.env.VITE_SWAGGER_DOCS_API_URI,
}