export const importData = {
    NEXT_PUBLIC_FARMFARM_SERVER_URL: process.env.NEXT_PUBLIC_FARMFARM_SERVER_URL,
    NEXT_PUBLIC_AUTH_SERVER_URL: process.env.NEXT_PUBLIC_AUTH_SERVER_URL,
    NEXT_PUBLIC_AUTH_SERVER_REALM: process.env.NEXT_PUBLIC_AUTH_SERVER_REALM,
    NEXT_PUBLIC_SWAGGER_DOCS_API_URI: process.env.NEXT_PUBLIC_SWAGGER_DOCS_API_URI,
}