/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GreenhouseSectionSensor,
  GreenhouseSectionSensorCreateForm
} from '../../model'
import { farmfarmAxiosInstance } from '../../../axios/axios_instance';
import type { ErrorType, BodyType } from '../../../axios/axios_instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


export const findAllGreenhouseSectionSensor = (
    greenhouseId: string,
    greenhouseSectionId: string,
 options?: SecondParameter<typeof farmfarmAxiosInstance>,signal?: AbortSignal
) => {
      
      
      return farmfarmAxiosInstance<GreenhouseSectionSensor[]>(
      {url: `/greenhouses/${greenhouseId}/sections/${greenhouseSectionId}/sensors`, method: 'GET', signal
    },
      options);
    }
  

export const getFindAllGreenhouseSectionSensorQueryKey = (greenhouseId: string,
    greenhouseSectionId: string,) => {
    return [`/greenhouses/${greenhouseId}/sections/${greenhouseSectionId}/sensors`] as const;
    }

    
export const getFindAllGreenhouseSectionSensorQueryOptions = <TData = Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>, TError = ErrorType<unknown>>(greenhouseId: string,
    greenhouseSectionId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>, TError, TData>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllGreenhouseSectionSensorQueryKey(greenhouseId,greenhouseSectionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>> = ({ signal }) => findAllGreenhouseSectionSensor(greenhouseId,greenhouseSectionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(greenhouseId && greenhouseSectionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>, TError, TData> & { queryKey: QueryKey }
}

export type FindAllGreenhouseSectionSensorQueryResult = NonNullable<Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>>
export type FindAllGreenhouseSectionSensorQueryError = ErrorType<unknown>

export const useFindAllGreenhouseSectionSensor = <TData = Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>, TError = ErrorType<unknown>>(
 greenhouseId: string,
    greenhouseSectionId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof findAllGreenhouseSectionSensor>>, TError, TData>, request?: SecondParameter<typeof farmfarmAxiosInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getFindAllGreenhouseSectionSensorQueryOptions(greenhouseId,greenhouseSectionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const createGreenhouseSectionSensor = (
    greenhouseId: string,
    greenhouseSectionId: string,
    greenhouseSectionSensorCreateForm: BodyType<GreenhouseSectionSensorCreateForm>,
 options?: SecondParameter<typeof farmfarmAxiosInstance>,) => {
      
      
      return farmfarmAxiosInstance<string>(
      {url: `/greenhouses/${greenhouseId}/sections/${greenhouseSectionId}/sensors`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: greenhouseSectionSensorCreateForm
    },
      options);
    }
  


export const getCreateGreenhouseSectionSensorMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGreenhouseSectionSensor>>, TError,{greenhouseId: string;greenhouseSectionId: string;data: BodyType<GreenhouseSectionSensorCreateForm>}, TContext>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createGreenhouseSectionSensor>>, TError,{greenhouseId: string;greenhouseSectionId: string;data: BodyType<GreenhouseSectionSensorCreateForm>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGreenhouseSectionSensor>>, {greenhouseId: string;greenhouseSectionId: string;data: BodyType<GreenhouseSectionSensorCreateForm>}> = (props) => {
          const {greenhouseId,greenhouseSectionId,data} = props ?? {};

          return  createGreenhouseSectionSensor(greenhouseId,greenhouseSectionId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGreenhouseSectionSensorMutationResult = NonNullable<Awaited<ReturnType<typeof createGreenhouseSectionSensor>>>
    export type CreateGreenhouseSectionSensorMutationBody = BodyType<GreenhouseSectionSensorCreateForm>
    export type CreateGreenhouseSectionSensorMutationError = ErrorType<unknown>

    export const useCreateGreenhouseSectionSensor = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGreenhouseSectionSensor>>, TError,{greenhouseId: string;greenhouseSectionId: string;data: BodyType<GreenhouseSectionSensorCreateForm>}, TContext>, request?: SecondParameter<typeof farmfarmAxiosInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createGreenhouseSectionSensor>>,
        TError,
        {greenhouseId: string;greenhouseSectionId: string;data: BodyType<GreenhouseSectionSensorCreateForm>},
        TContext
      > => {

      const mutationOptions = getCreateGreenhouseSectionSensorMutationOptions(options);

      return useMutation(mutationOptions);
    }
    