/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import type { Organization } from './organization';
import type { GreenhouseStatus } from './greenhouseStatus';

export interface Greenhouse {
  createdAt?: string;
  id?: string;
  lastStatusUpdateAt?: string;
  organization?: Organization;
  status?: GreenhouseStatus;
  updatedAt?: string;
}
