/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import type { Greenhouse } from './greenhouse';

export interface GreenhouseSection {
  createdAt?: string;
  greenhouse?: Greenhouse;
  id?: string;
  sectionNumber?: number;
  updatedAt?: string;
}
