/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import type { GreenhouseSection } from './greenhouseSection';
import type { SensorModel } from './sensorModel';

export interface GreenhouseSectionSensor {
  adminName?: string;
  createdAt?: string;
  displayName?: string;
  greenhouseSection?: GreenhouseSection;
  id?: string;
  sensorModel?: SensorModel;
  updatedAt?: string;
}
