/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import type { GreenhouseSectionSensor } from './greenhouseSectionSensor';
import type { MeasurementType } from './measurementType';

export interface GreenhouseSectionSensorMeasurement {
  id?: string;
  measuredAt?: string;
  sensor?: GreenhouseSectionSensor;
  type?: MeasurementType;
  value?: number;
}
