/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */

export type GreenhouseStatus = typeof GreenhouseStatus[keyof typeof GreenhouseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GreenhouseStatus = {
  HEALTHY: 'HEALTHY',
  UNHEALTHY: 'UNHEALTHY',
  NOT_CREATED: 'NOT_CREATED',
} as const;
