/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import type { MeasurementTypeUnit } from './measurementTypeUnit';

export interface MeasurementType {
  createdAt?: string;
  id?: string;
  type?: string;
  unit?: MeasurementTypeUnit;
  updatedAt?: string;
}
