/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */

export type MeasurementTypeCreateFormUnit = typeof MeasurementTypeCreateFormUnit[keyof typeof MeasurementTypeCreateFormUnit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MeasurementTypeCreateFormUnit = {
  CELSIUS: 'CELSIUS',
  PERCENTAGE: 'PERCENTAGE',
} as const;
