/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */

export interface Organization {
  createdAt?: string;
  id?: string;
  name?: string;
  updatedAt?: string;
}
