/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 팜팜 API
 * 팜팜 API
 * OpenAPI spec version: 1.0.0
 */
import type { MeasurementType } from './measurementType';

export interface SensorModel {
  createdAt?: string;
  id?: string;
  measurementTypes?: MeasurementType[];
  modelName?: string;
  updatedAt?: string;
}
